### ISSUE TITLE
Long parameter names run into form field

### ISSUE THREAD

**Issue by ddaguro** [jensoleg/swagger-ui#18]
First of all, this is so awesome!  We are loving the bootstrap theme.

We did notice that some long parameter names will run into the form field. 

![screen shot 2015-06-23 at 9 42 55 am](https://cloud.githubusercontent.com/assets/13004715/8308794/8086f9b8-198c-11e5-8e67-f3b1a5bacc85.png)

**Comment by jensoleg** [comment]
Hi @ddaguro 

A possible solution is making the css overflow hidden on the label. This will cut the label and avoid flowing into the input field. 

Do you think of other solutions ?

**Comment by dmyers** [comment]
Yeah I've ran into this too, but I haven't though of a clean design style.

**Comment by ddaguro** [comment]
@jensoleg I think the oveflow hidden on label might be a good idea, especially if you're able to append an ellipse to indicate overflow.  Then perhaps upon hover it could use the title attribute to show the full name of the parameter.  I'll try to think of some other cleaner ways.

**Comment by jensoleg** [comment]
I have two  suggestions to solve this  

Abbreviate and mark with ellipsis:

white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;

![swagger explorer 2](https://cloud.githubusercontent.com/assets/5655197/8327856/fbd47c64-1a6b-11e5-9cb9-65acdb6fb09b.png)

Wrap the string with:

word-wrap: break-word;

![wrap](https://cloud.githubusercontent.com/assets/5655197/8327910/5a8ef536-1a6c-11e5-82ef-d79fb85a6f35.png)

I think abbreviating the text with ellipsis is the way to go ?

**Comment by jensoleg** [comment]
Added abbreviation of parameter text and tooltip. Tooltip is placed on input/textarea field. 

Commit: 8fdb4af7bb8c35d57b8d96befc1aad70fcb2e517

**Comment by ddaguro** [comment]
This is perfect!  And I like how the tooltip shows on hover of the form field.  Thumbs up.

**Comment by mike-seagull** [comment]
@jensoleg Would it be possible to make the parameter text above or below the input/textarea field?
