### ISSUE TITLE
Password field in plain text

### ISSUE THREAD

**Issue by ddaguro** [jensoleg/swagger-ui#22]
Looks like password fields are in plain text at the moment.  If they could be masked to match the behavior of the original swagger ui, that would be great. 

![screen shot 2015-07-08 at 8 10 24 am](https://cloud.githubusercontent.com/assets/13004715/8570881/fc6cd742-2548-11e5-993d-457586f85d6d.png)

**Comment by hemeroc** [comment]
The password field in the original swagger UI is also not masked, there is no way do differentiate a normal text field from a password field.
(see: http://petstore.swagger.io/#!/user/loginUser )

``` json
"parameters":[
   {
      "name":"username",
      "in":"query",
      "description":"The user name for login",
      "required":true,
      "type":"string"
   },
   {
      "name":"password",
      "in":"query",
      "description":"The password for login in clear text",
      "required":true,
      "type":"string"
   }
],
```

**Comment by ddaguro** [comment]
If your definition looks like this it will mask it in the Petstore UI.
 "format": "password"

{
                        "name": "username",
                        "in": "formData",
                        "description": "Username",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "password",
                        "in": "formData",
                        "description": "Password",
                        "required": true,
                        "type": "string",
                        "format": "password"
                    }

**Comment by jensoleg** [comment]
Updated the repo to handle input parameter password format
