### ISSUE TITLE
Support for fixed headers

### ISSUE THREAD

**Issue by tmcdonnell87** [jensoleg/swagger-ui#25]
Hi,

Great work - this looks amazing and so much better than the base Swagger UI. 

I'd love to add a fixed header to my swagger documentation. The one challenge is to offset by the header height when scrolling, but it's a bit hard to see what's going on in your scroll handler, since it's a minified javascript block in the index.html file. 

Is there source code anywhere?

Thanks,
Terry

**Comment by tmcdonnell87** [comment]
Also getting this error when using the URL link (out of the box code):

Uncaught TypeError: Cannot read property 'top' of undefined

i @ (index):132
(anonymous function) @ (index):120
p.event.dispatch @ jquery-1.8.0.min.js:2
p.event.add.g.handle.h @ jquery-1.8.0.min.js:2

Bit hard to debug through the minified code.

**Comment by jensoleg** [comment]
HI 

Try adding the class "fixed" to the sticky-nav (in main-handlebars) and add the class "navbar-fixed-top" to the navbar.

Uncomment or remove this line in the sticky bar js script: 
$(window).scrollTop() > navOffset ? $(".modal.in").length || n.addClass("fixed") : n.removeClass("fixed")

Now you need to fix the rest with css to get the navbar height and background fit
