### ISSUE TITLE
Response Sample Response Schema

### ISSUE THREAD

**Issue by mike-seagull** [jensoleg/swagger-ui#31]
The schema is in the block for sample.
![screen shot 2015-12-14 at 10 37 21 am](https://cloud.githubusercontent.com/assets/4307200/11786893/bac0dacc-a24e-11e5-8f82-346493c69e09.png)

**Comment by mike-seagull** [comment]
nvm my mistake :) u have to click on it to open it

**Comment by pdurkim** [comment]
how did you define a response sample?

**Comment by mike-seagull** [comment]
@peyterkim I defined it within the "responses" block in the json file https://crossbrowsertesting.com/apidocs/definitions/livetests.json https://crossbrowsertesting.com/apidocs/v3/livetests.html

**Comment by pdurkim** [comment]
so, i was using Swagger::Blocks because I'm trying to generate docs for a Rails app but the setup is kind of confusing. Seems like you are writing out the docs manually...what resources have you used to get this set up?

**Comment by pdurkim** [comment]
is there a way to define response examples for Swagger 1.2?
