### ISSUE TITLE
Any plans to keep this updated with Swagger-JS/Swagger-UI releases?

### ISSUE THREAD

**Issue by firefoxNX** [jensoleg/swagger-ui#34]
Hi Jens-Ole,

Do you have any plans on updating Swagger-JS and other Swagger-UI related dependencies?

**Comment by vccs** [comment]
+1

**Comment by jensoleg** [comment]
No I do not have time to follow the pace of changes in these modules. This is a deviation of the swagger-ui and some change may be relevant others not. The latest swagger specification 2.0 features should be available

**Comment by vincent815** [comment]
+1
