### ISSUE TITLE
Default textarea input extra spacing

### ISSUE THREAD

**Issue by dmyers** [jensoleg/swagger-ui#4]
I noticed there is some spacing automatically in the textarea inputs. Also the demo url in the readme seems to be moved/gone?

This is what it looks like:
![screen shot 2015-05-26 at 2 16 32 pm](https://cloud.githubusercontent.com/assets/207171/7821063/dc87d278-03b1-11e5-86e9-942096e79968.png)

If I remove the text:
![screen shot 2015-05-26 at 2 16 36 pm](https://cloud.githubusercontent.com/assets/207171/7821067/e6699bfa-03b1-11e5-8712-71fc0dc238fa.png)

I tested this with the default swagger pet API and it does the same thing. I think this changed recently if that helps. I'm still trying to figure out how to fix it.

**Comment by jensoleg** [comment]
@dmyers I fixed the body textarea obscurity ... please [check it](http://senodio.com/site/swagger) at the new address (README updated). You should also notice that you can click on the body sample and have it copied to the body input area. 

The collapse should still be there, but I am not quiet sure what you mean ? There is a new vertical collapse button/link "Show samples" which slides the samples and schema into the view when they are partially hidden.  

![image](https://cloud.githubusercontent.com/assets/5655197/7822804/47ca9818-03f8-11e5-8218-1aafcb9c591f.png)

**Comment by dmyers** [comment]
Sweet thanks on the textarea spacing, looks good on there now.

Oh I see in now, it was my browser resolution was wide enough that it hid it. Very nice it looks great! Thanks.

**Comment by jensoleg** [comment]
Great :+1: 

Also notice you can link directly to the operations now from the browser address filed (or document links) - try http://senodio.com/site/swagger/#!/store/getInventory  to go directly to the "pet inventory"

**Comment by dmyers** [comment]
That is awesome!
