### ISSUE TITLE
Integrate JSON Body Editor

### ISSUE THREAD

**Issue by faresd** [jensoleg/swagger-ui#46]
This is a proposal to integrate JSON editor for body requests in the UI, this feature is already implemented in the original project of swagger-ui, and for the related commit on swagger-ui click [here](https://github.com/swagger-api/swagger-ui/commit/dbf00bba5b9459fee6db6e3795ed6f158242f61b), this code uses a library called : [JSON Schema Based Editor](https://github.com/jdorn/json-editor/)
This is a snapshot of the example of the native JSONEditor in swagger UI 

![image](https://cloud.githubusercontent.com/assets/1819120/14608838/96025fe8-0587-11e6-8ea9-fa5a242e2cbe.png)

The file index.html should be configurable as (jsonEditor: true).
Thanks,

**Comment by faresd** [comment]
I've integrated the JSON editor and created a pull request:
[https://github.com/jensoleg/swagger-ui/pull/48](https://github.com/jensoleg/swagger-ui/pull/48)

**Comment by faresd** [comment]
Updated pull request: 
[https://github.com/jensoleg/swagger-ui/pull/51](https://github.com/jensoleg/swagger-ui/pull/51)

**Comment by jensoleg** [comment]
Thanks @faresd . This is now merged with a little styling of the buttons.

**Comment by faresd** [comment]
Cool! thanks @jensoleg.
