### ISSUE TITLE
Operation code model-signature class

### ISSUE THREAD

**Issue by dmyers** [jensoleg/swagger-ui#5]
I noticed Auth0 has a `model-signature` class on the `<code>` tags which makes them gray and you can still use the code tag in descriptions for emphasis.

![screen shot 2015-05-26 at 5 58 29 pm](https://cloud.githubusercontent.com/assets/207171/7825285/d92f80d4-03d0-11e5-832d-99a7a3351419.png)

Do you like that? I tried to get a PR with it, but it got messed up on body parameters.

**Comment by jensoleg** [comment]
Fixed it. Is it ok now ?

**Comment by dmyers** [comment]
Thanks! That looks great! I'm glad you liked it too.
