### ISSUE TITLE
Custom schema titles

### ISSUE THREAD

**Issue by dmyers** [jensoleg/swagger-ui#7]
Hey @jensoleg have you tried setting a title property on a schema? I've found that the current regular swagger UI is not picking it up and using it.

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object

https://github.com/swagger-api/swagger-js/pull/342#issuecomment-106004648

![ss3](https://cloud.githubusercontent.com/assets/207171/7843056/d7138754-046c-11e5-9b8d-f8a20c97991c.png)

![ss4](https://cloud.githubusercontent.com/assets/207171/7843060/daec1c24-046c-11e5-983d-9a027b5d05ed.png)

This file did change, maybe updating https://github.com/jensoleg/swagger-js might help?
https://github.com/swagger-api/swagger-js/blob/master/lib/types/model.js#L42

**Comment by jensoleg** [comment]
Yes I've noticed there is a problem with BODY schemas and arrays, but haven't tried out with title properties. Can you provide an example swagger file and point out what you want ?

**Comment by dmyers** [comment]
Oh okay. I tried debugging in swagger-js for a long time and couldn't figure it out.

I added them today to change how it would show the schema model names. I have an example below if it helps:
https://api.monscierge.com/swagger/docs/v1

I appreciate all of your help. I'm really excited to use this. :+1: :smile:

**Comment by jensoleg** [comment]
swagger-js is a tricky beast :smile:  
Try to update the swagger-client from my github repo - npm update swagger-client and see if this is better ?

**Comment by dmyers** [comment]
Yeah it did improve some, though there was a few other spots that were still referencing the non schema title like in the response schema.

**Comment by jensoleg** [comment]
I have merged your pull requests and updated the client libraries in swagger-js.

Getting better and better - thanks :smile:

**Comment by dmyers** [comment]
Thanks. Yeah it really is! :+1:

**Comment by jensoleg** [comment]
It looks nice with the Concierge API but when I test the Swagger Pet Store Api there are some problems with undefined titles.

![swagger explorer 1](https://cloud.githubusercontent.com/assets/5655197/7872137/f5516342-0595-11e5-8104-1cea57a21204.png)

Any idea ?

**Comment by dmyers** [comment]
Oops was it the last change? I will check.

**Comment by jensoleg** [comment]
Really don't know but I guess it could be. Didn't notice it before now. You can try to roll the change back in the swagger-ui.js file in the dist folder and check if that is the problem.

**Comment by dmyers** [comment]
Okay I think I figured it out. There is a value that is passing not null, but is also undefined.
