### ISSUE TITLE
Global path parameters don't work

### ISSUE THREAD

**Issue by beardedlinuxgeek** [jensoleg/swagger-ui#73]
Support was added in swagger-ui v2.1.3-M2

https://github.com/swagger-api/swagger-ui/issues/911

I've actually been able to fix this though. I changed the swagger-js target in package.json from your fork to the latest version in the official branch. When I rebuilt this fork of swagger-ui, global parameters started working automatically and there were no issues with using the master branch of swagger-js instead of your fork. I would recommend updating the package.json and rebuilding dist so that other users can have this feature as well.

**Comment by aeros0ul** [comment]
@beardedlinuxgeek 
you could have allowed us to participate in your work/improvements by just adding a pull request.
