### ISSUE TITLE
Sandbox response body and header syntax highlighting

### ISSUE THREAD

**Issue by dmyers** [jensoleg/swagger-ui#8]
Would it be useful? I've been trying to get it to use the same highlight code after sending a request, but haven't gotten it to work.

**Comment by jensoleg** [comment]
I've fixed it. Unfortunately some of the code in OperationView was commented out. Swagger uses the [highlight.js](https://highlightjs.org/) library for syntax highlighting the responses.

Next week I will try to add the request and response content-type to the UI. This is missing at the moment. On vacation the next days :+1:

**Comment by jensoleg** [comment]
OK just reached to add a response content selection box - have fun !

**Comment by dmyers** [comment]
Oh I gotcha. That looks really great, thank you. :+1: Enjoy your time off, you earned it!
