### ISSUE TITLE
Dropdowns to allow null values

### ISSUE THREAD

**Issue by dmyers** [jensoleg/swagger-ui#9]
It might be neat to allow dropdowns to send a null value rather than sending the default as the server will already have the default. I noticed Auth0 has their dropdowns as blank (null) at first and then  you choose one. Not sure if this is a good idea or not just thought I'd mention and see what you thought.

https://auth0.com/docs/api/v2#!/Clients/get_clients

**Comment by jensoleg** [comment]
You are right a value should not be enforced. I will look into it.

**Comment by jensoleg** [comment]
The parameter dropdown list is modified to allow null values if the parameter is not required or has a default value. See the param_list.handlebars file for details/logic.

Also added dropdown to select body content type.
